/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ClienteDao;
import br.edu.ifnmg.trabalho.DataAccess.ProdutoDao;
import br.edu.ifnmg.trabalho.classes.Cliente;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Produto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author emerson
 */
public class frmClienteEditar extends javax.swing.JInternalFrame {
    Cliente cliente;
    ClienteDao dao;
    /**
     * Creates new form frmProdutoEditar
     */
    public frmClienteEditar(Cliente c, ClienteDao d) {
        initComponents();
        this.cliente = c;
        this.dao = d;
        
        carregaCampos();
       
    }

    frmClienteEditar(Produto cliente, ClienteDao dao) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
     private void carregaCampos() {
        txtEditarClienId.setText(Integer.toString(cliente.getId()));
        txtEditarClienNome.setText(cliente.getNome());
        txtEditarClienCpf.setText(Integer.toString(cliente.getCpf()));
        txtEditarClienRg.setText(Integer.toString(cliente.getRg()));
        
        SimpleDateFormat formatoData = new SimpleDateFormat("yyyyMMdd");
       
        txtEditarClienNascimento.setText(formatoData.format(cliente.getData()));
       
    }

    private void carregaObjeto() {
        try{
        cliente.setId(Integer.parseInt(txtEditarClienId.getText()));
        cliente.setNome(txtEditarClienNome.getText());
        cliente.setCpf(Integer.parseInt(txtEditarClienCpf.getText()));
        cliente.setRg(Integer.parseInt(txtEditarClienRg.getText()));
        
        
        }catch (ErroValidacaoException ex){
            System.out.print("Erro");
        }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTituloProdutoEditar = new javax.swing.JPanel();
        lblTituloProdutoEditar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEditarClienNome = new javax.swing.JTextField();
        txtEditarClienCpf = new javax.swing.JTextField();
        txtEditarClienRg = new javax.swing.JTextField();
        btnAlterarProduto = new javax.swing.JButton();
        btnCancelarEdicaoProduto = new javax.swing.JButton();
        txtEditarClienId = new javax.swing.JTextField();
        btnApagarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEditarClienNascimento = new javax.swing.JTextField();

        setClosable(true);

        jpTituloProdutoEditar.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloProdutoEditar.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloProdutoEditar.setText("Editar Cliente");

        javax.swing.GroupLayout jpTituloProdutoEditarLayout = new javax.swing.GroupLayout(jpTituloProdutoEditar);
        jpTituloProdutoEditar.setLayout(jpTituloProdutoEditarLayout);
        jpTituloProdutoEditarLayout.setHorizontalGroup(
            jpTituloProdutoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloProdutoEditarLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lblTituloProdutoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTituloProdutoEditarLayout.setVerticalGroup(
            jpTituloProdutoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloProdutoEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloProdutoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Id");

        jLabel3.setText("Nome");

        jLabel4.setText("Cpf");

        jLabel5.setText("Rg");

        txtEditarClienCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarClienCpfActionPerformed(evt);
            }
        });

        txtEditarClienRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarClienRgActionPerformed(evt);
            }
        });

        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnCancelarEdicaoProduto.setText("Limpar");
        btnCancelarEdicaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEdicaoProdutoActionPerformed(evt);
            }
        });

        txtEditarClienId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEditarClienId.setEnabled(false);

        btnApagarProduto.setText("Apagar");
        btnApagarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloProdutoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEditarClienId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditarClienNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(txtEditarClienCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(txtEditarClienRg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEditarClienNascimento))))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApagarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarEdicaoProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloProdutoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditarClienId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarClienNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEditarClienCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarClienRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtEditarClienNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarEdicaoProduto)))
                .addGap(0, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditarClienRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarClienRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarClienRgActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Salvar?") == 0) {

                carregaObjeto();
                
                if (dao.Salvar(cliente)) {
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmClienteListar janela = new frmClienteListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                 
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao salvar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void btnApagarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarProdutoActionPerformed
         try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente apagar este produto?") == 0) {

                carregaObjeto();
                
                if (dao.Apagar(cliente)) {
                    JOptionPane.showMessageDialog(rootPane, "Produto deletado com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmClienteListar janela = new frmClienteListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao apagar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnApagarProdutoActionPerformed

    private void txtEditarClienCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarClienCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarClienCpfActionPerformed

    private void btnCancelarEdicaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicaoProdutoActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar os seguintes campos?") == 0) {
            txtEditarClienNome.setText(null);
            txtEditarClienCpf.setText(null);
            txtEditarClienRg.setText(null);
            txtEditarClienNascimento.setText(null);
           
            
            JOptionPane.showMessageDialog(rootPane, "Os Campos foram limpos!");
   
        } else {                
            JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
        }
    }//GEN-LAST:event_btnCancelarEdicaoProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnApagarProduto;
    private javax.swing.JButton btnCancelarEdicaoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jpTituloProdutoEditar;
    private javax.swing.JLabel lblTituloProdutoEditar;
    private javax.swing.JTextField txtEditarClienCpf;
    private javax.swing.JTextField txtEditarClienId;
    private javax.swing.JTextField txtEditarClienNascimento;
    private javax.swing.JTextField txtEditarClienNome;
    private javax.swing.JTextField txtEditarClienRg;
    // End of variables declaration//GEN-END:variables
}
