/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ClienteDao;
import br.edu.ifnmg.trabalho.classes.Cliente;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author emerson
 */
public class frmClienteEditar extends javax.swing.JInternalFrame {
    Cliente  cliente;
    ClienteDao dao;

    /**
     * Creates new form frmClienteEditar
     */
    public frmClienteEditar(Cliente c, ClienteDao d) throws ErroValidacaoException, ParseException {
        initComponents();
        this.cliente = c;
        this.dao = d;
        
        carregaCampos();
    }
    
    public Date DataF(String dataDesformatada) throws ParseException{
        
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");  
        Date dataForm = format.parse(dataDesformatada);
        
      
        return dataForm; 
    }
    
    private void carregaCampos() throws ErroValidacaoException, ParseException {
        txtEditarClienteId.setText(Integer.toString(cliente.getId()));
        txtEditarClienteNome.setText(cliente.getNome());
        txtEditarClienteCpf.setText(Integer.toString(cliente.getCpf()));
        txtEditarClienteRg.setText(Integer.toString(cliente.getRg()));
        txtEditarClienteNascimento.setText(cliente.getDataRetorno());

    }

    private void carregaObjeto() {
        try{
        cliente.setId(Integer.parseInt(txtEditarClienteId.getText()));
        cliente.setNome(txtEditarClienteNome.getText());
        cliente.setCpf(Integer.parseInt(txtEditarClienteCpf.getText()));
        cliente.setRg(Integer.parseInt(txtEditarClienteRg.getText()));
        cliente.setData(DataF(txtEditarClienteNascimento.getText()));
      
        }catch (Exception ex){
            System.out.print("Erro");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEditarClienteId = new javax.swing.JTextField();
        txtEditarClienteNome = new javax.swing.JTextField();
        txtEditarClienteCpf = new javax.swing.JTextField();
        txtEditarClienteRg = new javax.swing.JTextField();
        txtEditarClienteNascimento = new javax.swing.JTextField();
        btnEditarClienteApagar = new javax.swing.JButton();
        btnEditarClienteSalvar = new javax.swing.JButton();
        jpTituloPagamentoEditar = new javax.swing.JPanel();
        lblTituloPagamentoEditar = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Id");

        jLabel2.setText("Nome");

        jLabel3.setText("Cpf");

        jLabel4.setText("Rg");

        jLabel5.setText("Nascimento");

        txtEditarClienteId.setEnabled(false);

        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##-##-####");
            txtEditarClienteNascimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        btnEditarClienteApagar.setText("Apagar");
        btnEditarClienteApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteApagarActionPerformed(evt);
            }
        });

        btnEditarClienteSalvar.setText("Salvar");
        btnEditarClienteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteSalvarActionPerformed(evt);
            }
        });

        jpTituloPagamentoEditar.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloPagamentoEditar.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloPagamentoEditar.setText("Editar Cliente");

        javax.swing.GroupLayout jpTituloPagamentoEditarLayout = new javax.swing.GroupLayout(jpTituloPagamentoEditar);
        jpTituloPagamentoEditar.setLayout(jpTituloPagamentoEditarLayout);
        jpTituloPagamentoEditarLayout.setHorizontalGroup(
            jpTituloPagamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloPagamentoEditarLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(lblTituloPagamentoEditar)
                .addGap(210, 210, 210))
        );
        jpTituloPagamentoEditarLayout.setVerticalGroup(
            jpTituloPagamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloPagamentoEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPagamentoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEditarClienteId, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(txtEditarClienteNome)
                    .addComponent(txtEditarClienteCpf)
                    .addComponent(txtEditarClienteRg)
                    .addComponent(txtEditarClienteNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarClienteApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarClienteSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addComponent(jpTituloPagamentoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloPagamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEditarClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEditarClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEditarClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtEditarClienteRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtEditarClienteNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarClienteSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarClienteApagar)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarClienteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteSalvarActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Salvar?") == 0) {

                carregaObjeto();
                
                if (dao.Salvar(cliente)) {
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmClienteListar janela = new frmClienteListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao salvar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnEditarClienteSalvarActionPerformed

    private void btnEditarClienteApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteApagarActionPerformed
       try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente apagar cliente?") == 0) {

                carregaObjeto();
                
                if (dao.Apagar(cliente)) {
                    JOptionPane.showMessageDialog(rootPane, "Cliente deletado com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmClienteListar janela = new frmClienteListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao apagar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnEditarClienteApagarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarClienteApagar;
    private javax.swing.JButton btnEditarClienteSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jpTituloPagamentoEditar;
    private javax.swing.JPanel jpTituloPagamentoEditar1;
    private javax.swing.JPanel jpTituloPagamentoEditar2;
    private javax.swing.JPanel jpTituloPagamentoEditar3;
    private javax.swing.JPanel jpTituloPagamentoEditar4;
    private javax.swing.JPanel jpTituloPagamentoEditar5;
    private javax.swing.JLabel lblTituloPagamentoEditar;
    private javax.swing.JLabel lblTituloPagamentoEditar1;
    private javax.swing.JLabel lblTituloPagamentoEditar2;
    private javax.swing.JLabel lblTituloPagamentoEditar3;
    private javax.swing.JLabel lblTituloPagamentoEditar4;
    private javax.swing.JLabel lblTituloPagamentoEditar5;
    private javax.swing.JTextField txtEditarClienteCpf;
    private javax.swing.JTextField txtEditarClienteId;
    private javax.swing.JTextField txtEditarClienteNascimento;
    private javax.swing.JTextField txtEditarClienteNome;
    private javax.swing.JTextField txtEditarClienteRg;
    // End of variables declaration//GEN-END:variables
}
