/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ClienteDao;
import br.edu.ifnmg.trabalho.classes.Cliente;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author emerson
 */
public class frmClienteListar extends javax.swing.JInternalFrame {
    ClienteDao dao;
    /**
     * Creates new form frmListarProduto
     */
    public frmClienteListar() throws ErroValidacaoException {
        initComponents();
        dao = new ClienteDao();
        
        List<Cliente> clientes = dao.listarTodos();
        
        preencheTabela(clientes);
    }
    
    //Metodo para listar Produtos na Tabela tblListagemProd
    private void preencheTabela(List<Cliente> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nome");
        model.addColumn("Cpf");
        model.addColumn("Rg");
        model.addColumn("Nascimento");

        
        for (Cliente cliente : lista) {
            Vector valores = new Vector();
            valores.add(0,cliente.getId());
            valores.add(1,cliente.getNome());
            valores.add(2,cliente.getCpf());
            valores.add(3,cliente.getRg());
            valores.add(4,cliente.getData());
            
            model.addRow(valores);
        }
        tblListagemCliente.setModel(model);
        tblListagemCliente.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProd = new javax.swing.JLabel();
        txtFiltrarCliente = new javax.swing.JTextField();
        btnFiltrarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagemCliente = new javax.swing.JTable();
        jpTituloProdutoListar = new javax.swing.JPanel();
        lblTituloProdutoListar = new javax.swing.JLabel();
        lblTituloClienteListar = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(600, 380));

        lblNomeProd.setText("Nome");

        btnFiltrarCliente.setText("Filtrar");
        btnFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarClienteActionPerformed(evt);
            }
        });

        tblListagemCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListagemCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagemCliente);

        jpTituloProdutoListar.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloProdutoListar.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        lblTituloProdutoListar.setText("Clique sobre o produto para editar.");

        lblTituloClienteListar.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloClienteListar.setText("Listagem de Clientes");

        javax.swing.GroupLayout jpTituloProdutoListarLayout = new javax.swing.GroupLayout(jpTituloProdutoListar);
        jpTituloProdutoListar.setLayout(jpTituloProdutoListarLayout);
        jpTituloProdutoListarLayout.setHorizontalGroup(
            jpTituloProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloProdutoListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTituloProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloProdutoListarLayout.createSequentialGroup()
                        .addComponent(lblTituloProdutoListar)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloProdutoListarLayout.createSequentialGroup()
                        .addComponent(lblTituloClienteListar)
                        .addGap(167, 167, 167))))
        );
        jpTituloProdutoListarLayout.setVerticalGroup(
            jpTituloProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloProdutoListarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloClienteListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloProdutoListar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloProdutoListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrarCliente)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloProdutoListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProd)
                    .addComponent(btnFiltrarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarClienteActionPerformed
        Cliente clien = new Cliente();
        try {
            clien.setNome(txtFiltrarCliente.getText());
        } catch (ErroValidacaoException ex) {
            System.out.printf("Erro");
        }
        
        List<Cliente> lista = null;
        try {
            lista = dao.buscar(clien);
        } catch (ErroValidacaoException ex) {
            System.out.printf("Erro");
        }
        
        preencheTabela(lista);
    }//GEN-LAST:event_btnFiltrarClienteActionPerformed

    private void tblListagemClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemClienteMouseClicked
        Object valor = tblListagemCliente.getValueAt( tblListagemCliente.getSelectedRow(), 0);
        Cliente cliente = null;
        try {
            cliente = dao.Abrir((int)valor);
        } catch (ErroValidacaoException ex) {
            System.out.printf("Erro");        }
        frmClienteEditar janela = new frmClienteEditar(cliente, dao);
        this.getParent().add(janela);
        janela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tblListagemClienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpTituloProdutoListar;
    private javax.swing.JLabel lblNomeProd;
    private javax.swing.JLabel lblTituloClienteListar;
    private javax.swing.JLabel lblTituloProdutoListar;
    private javax.swing.JTable tblListagemCliente;
    private javax.swing.JTextField txtFiltrarCliente;
    // End of variables declaration//GEN-END:variables
}
