/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.FuncionarioDao;
import br.edu.ifnmg.trabalho.classes.Email;
import br.edu.ifnmg.trabalho.classes.Endereco;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Funcionario;
import br.edu.ifnmg.trabalho.classes.Telefone;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author emerson
 */
public class frmFuncionarioCad extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProdutoInterno
     */
    Funcionario funcionario = new Funcionario();
    
     
    private void addCamposTelefone() {
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Numero Telefone");

       for (Telefone te : funcionario.getTelefones()) {
           Vector v = new Vector();
           v.add(te.getNum()); 
           model.addRow(v);
       }

       jtbCadListarTelefoneFuncionario.setModel(model);
    }
    //Add Email
    private void addCamposEmail() {
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("E-mail");

       for (Email email : funcionario.getEmails()) {
           Vector v = new Vector();
           v.add(email.getEmail_nome()); 
           model.addRow(v);
       }

       jtbFunListarEmail.setModel(model);
    }
    
     //Add Email
    private void addCamposEndereco() {
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Rua");
        model.addColumn("Num");
        model.addColumn("Bairro");
        

       for (Endereco endereco : funcionario.getEnderecos()) {
           Vector v = new Vector();
           // v.add(0,endereco.getId());
           v.add(0,endereco.getRua());
           v.add(1,endereco.getNum());
           v.add(2,endereco.getBairro());
            
           model.addRow(v);
       }

       jtbCadListarEndFuncionario.setModel(model);
    }
    
    public Date DataF(String dataDesformatada) throws ParseException{
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");  
        
        Date dataForm = format.parse(dataDesformatada);
        
        return dataForm; 
    }
    
    public frmFuncionarioCad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTituloClienteCad = new javax.swing.JPanel();
        lblTituloClienteCad = new javax.swing.JLabel();
        jtbClienteCad = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblClienteCadNome = new javax.swing.JLabel();
        lblCpfCad = new javax.swing.JLabel();
        lblRgCad = new javax.swing.JLabel();
        lblNascimentoCad = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtCpfFuncionario = new javax.swing.JTextField();
        txtRgFuncionario = new javax.swing.JTextField();
        txtNascimentoFuncionario = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            txtNascimentoFuncionario = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioFuncionario = new javax.swing.JTextField();
        pswSenhaCliente = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbCadListarTelefoneFuncionario = new javax.swing.JTable();
        lblCadClienteEmail1 = new javax.swing.JLabel();
        txtCadtelefoneFuncionario = new javax.swing.JTextField();
        btnFuncionarioCadTelefone = new javax.swing.JButton();
        jpTituloRemoverItemTabTelefone = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbFunListarEmail = new javax.swing.JTable();
        lblCadClienteEmail = new javax.swing.JLabel();
        txtCadEmailFuncionario = new javax.swing.JTextField();
        btnFuncionarioCadEmail = new javax.swing.JButton();
        jpTituloRemoverItemTabEmail = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCadListarEndFuncionario = new javax.swing.JTable();
        lblCadClienteRua = new javax.swing.JLabel();
        lblCadClienteNumero = new javax.swing.JLabel();
        lblCadClienteBairro = new javax.swing.JLabel();
        txtCadFuncionarioRua = new javax.swing.JTextField();
        txtCadFuncionarioNumero = new javax.swing.JTextField();
        txtCadFuncionarioBairro = new javax.swing.JTextField();
        btnFuncionarioCadEndeEditar = new javax.swing.JButton();
        btnFuncionarioCadEndeLimpar = new javax.swing.JButton();
        jpRemoverItemtbEndereco = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnFinalizarFuncionario = new javax.swing.JButton();
        btnLimparFuncionario = new javax.swing.JButton();
        btnCancelarFuncionario = new javax.swing.JButton();

        setClosable(true);

        jpTituloClienteCad.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloClienteCad.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloClienteCad.setText("Cadastrar Funcionario");

        javax.swing.GroupLayout jpTituloClienteCadLayout = new javax.swing.GroupLayout(jpTituloClienteCad);
        jpTituloClienteCad.setLayout(jpTituloClienteCadLayout);
        jpTituloClienteCadLayout.setHorizontalGroup(
            jpTituloClienteCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloClienteCadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloClienteCad)
                .addGap(162, 162, 162))
        );
        jpTituloClienteCadLayout.setVerticalGroup(
            jpTituloClienteCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloClienteCadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloClienteCad)
                .addContainerGap())
        );

        lblClienteCadNome.setText("Nome");

        lblCpfCad.setText("Cpf");

        lblRgCad.setText("Rg");

        lblNascimentoCad.setText("Data Nascimento");

        txtNomeFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFuncionarioFocusLost(evt);
            }
        });

        jLabel4.setText("Usuario");

        jLabel5.setText("Senha");

        pswSenhaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblClienteCadNome))
                            .addComponent(lblCpfCad, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(txtCpfFuncionario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblRgCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lblNascimentoCad)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNascimentoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(txtUsuarioFuncionario)
                            .addComponent(pswSenhaCliente))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteCadNome)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCad)
                    .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRgCad)
                    .addComponent(txtRgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimentoCad)
                    .addComponent(txtNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pswSenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jtbClienteCad.addTab("Geral", jPanel1);

        jtbCadListarTelefoneFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbCadListarTelefoneFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCadListarTelefoneFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtbCadListarTelefoneFuncionario);

        lblCadClienteEmail1.setText("Fone");

        btnFuncionarioCadTelefone.setText("Adicionar");
        btnFuncionarioCadTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioCadTelefoneActionPerformed(evt);
            }
        });

        jpTituloRemoverItemTabTelefone.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel1.setText("Clique sobre algum campo na tabela para deleta-lo ");

        javax.swing.GroupLayout jpTituloRemoverItemTabTelefoneLayout = new javax.swing.GroupLayout(jpTituloRemoverItemTabTelefone);
        jpTituloRemoverItemTabTelefone.setLayout(jpTituloRemoverItemTabTelefoneLayout);
        jpTituloRemoverItemTabTelefoneLayout.setHorizontalGroup(
            jpTituloRemoverItemTabTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloRemoverItemTabTelefoneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        jpTituloRemoverItemTabTelefoneLayout.setVerticalGroup(
            jpTituloRemoverItemTabTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloRemoverItemTabTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTituloRemoverItemTabTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCadClienteEmail1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadtelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnFuncionarioCadTelefone)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFuncionarioCadTelefone)
                    .addComponent(txtCadtelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteEmail1))
                .addGap(38, 38, 38)
                .addComponent(jpTituloRemoverItemTabTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jtbClienteCad.addTab("Telefones", jPanel3);

        jtbFunListarEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbFunListarEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbFunListarEmailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtbFunListarEmail);

        lblCadClienteEmail.setText("Email");

        btnFuncionarioCadEmail.setText("Adicionar");
        btnFuncionarioCadEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioCadEmailActionPerformed(evt);
            }
        });

        jpTituloRemoverItemTabEmail.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setText("Clique sobre algum campo na tabela para deleta-lo ");

        javax.swing.GroupLayout jpTituloRemoverItemTabEmailLayout = new javax.swing.GroupLayout(jpTituloRemoverItemTabEmail);
        jpTituloRemoverItemTabEmail.setLayout(jpTituloRemoverItemTabEmailLayout);
        jpTituloRemoverItemTabEmailLayout.setHorizontalGroup(
            jpTituloRemoverItemTabEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloRemoverItemTabEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );
        jpTituloRemoverItemTabEmailLayout.setVerticalGroup(
            jpTituloRemoverItemTabEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloRemoverItemTabEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCadClienteEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnFuncionarioCadEmail))
                    .addComponent(jpTituloRemoverItemTabEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFuncionarioCadEmail)
                    .addComponent(txtCadEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteEmail))
                .addGap(43, 43, 43)
                .addComponent(jpTituloRemoverItemTabEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jtbClienteCad.addTab("E-mails", jPanel4);

        jtbCadListarEndFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbCadListarEndFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCadListarEndFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCadListarEndFuncionario);

        lblCadClienteRua.setText("Rua");

        lblCadClienteNumero.setText("Numero");

        lblCadClienteBairro.setText("Bairro");

        txtCadFuncionarioNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioNumeroActionPerformed(evt);
            }
        });

        btnFuncionarioCadEndeEditar.setText("Adicionar");
        btnFuncionarioCadEndeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioCadEndeEditarActionPerformed(evt);
            }
        });

        btnFuncionarioCadEndeLimpar.setText("Limpar");

        jpRemoverItemtbEndereco.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setText("Clique sobre algum campo na tabela para deleta-lo ");

        javax.swing.GroupLayout jpRemoverItemtbEnderecoLayout = new javax.swing.GroupLayout(jpRemoverItemtbEndereco);
        jpRemoverItemtbEndereco.setLayout(jpRemoverItemtbEnderecoLayout);
        jpRemoverItemtbEnderecoLayout.setHorizontalGroup(
            jpRemoverItemtbEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRemoverItemtbEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(104, 104, 104))
        );
        jpRemoverItemtbEnderecoLayout.setVerticalGroup(
            jpRemoverItemtbEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRemoverItemtbEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCadClienteNumero)
                                .addComponent(lblCadClienteRua))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblCadClienteBairro)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCadFuncionarioBairro)
                            .addComponent(txtCadFuncionarioRua, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtCadFuncionarioNumero))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnFuncionarioCadEndeEditar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFuncionarioCadEndeLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpRemoverItemtbEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCadClienteRua)
                        .addComponent(txtCadFuncionarioRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFuncionarioCadEndeEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadClienteNumero)
                    .addComponent(txtCadFuncionarioNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFuncionarioCadEndeLimpar))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadClienteBairro)
                    .addComponent(txtCadFuncionarioBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jpRemoverItemtbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jtbClienteCad.addTab("Endereços", jPanel2);

        btnFinalizarFuncionario.setText("Adicionar");
        btnFinalizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarFuncionarioActionPerformed(evt);
            }
        });

        btnLimparFuncionario.setText("Limpar");
        btnLimparFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFuncionarioActionPerformed(evt);
            }
        });

        btnCancelarFuncionario.setText("Cancelar");
        btnCancelarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloClienteCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbClienteCad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloClienteCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbClienteCad, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarFuncionario)
                    .addComponent(btnLimparFuncionario)
                    .addComponent(btnFinalizarFuncionario))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFuncionarioActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane,  "Deseja Cancelar?") == 0){
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane,"Operação Não cancelada!");

        }

    }//GEN-LAST:event_btnCancelarFuncionarioActionPerformed

    private void btnLimparFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFuncionarioActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar os seguintes campos?") == 0) {
            txtNomeFuncionario.setText(null);
            txtCpfFuncionario.setText(null);
            txtRgFuncionario.setText(null);
            txtNascimentoFuncionario.setText(null);
            txtUsuarioFuncionario.setText(null);
            pswSenhaCliente.setText(null);
          
            JOptionPane.showMessageDialog(rootPane, "Os Campos foram limpos!");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
        }
    }//GEN-LAST:event_btnLimparFuncionarioActionPerformed

    private void btnFinalizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarFuncionarioActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane,  "Deseja Salvar?") == 0){
            try {
                
                //Setando os dados e convertendo de text para seus respectivos tipos.
                funcionario.setNome(txtNomeFuncionario.getText());
                funcionario.setCpf(Integer.parseInt(txtCpfFuncionario.getText()));
                funcionario.setRg(Integer.parseInt(txtRgFuncionario.getText()));
                funcionario.setUsuario(txtUsuarioFuncionario.getText());
                funcionario.setSenha(pswSenhaCliente.getText());
                
                try {
                    funcionario.setData(DataF(txtNascimentoFuncionario.getText()));
                } catch (ParseException ex) {
                    System.out.printf("Erro ao pegar a data do formulario Funcionario");
                }
                //Criando variavel dao para salvar os dados no BD.
                FuncionarioDao dao = new FuncionarioDao();
   
                try {
                    //mandando prod para dao.Salvar.
                    //Mensagem de confirmação!
                    if(dao.Salvar(funcionario,1)){
                        JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frmClienteCad.class.getName()).log(Level.SEVERE, null, ex);
                }

                //Limpando campos do formularios para o usuarios nao inserir os mesmos dados novamente.
                txtNomeFuncionario.setText(null);
                txtCpfFuncionario.setText(null);
                txtRgFuncionario.setText(null);
                txtNascimentoFuncionario.setText(null);
                txtUsuarioFuncionario.setText(null);
                pswSenhaCliente.setText(null);

            } catch (ErroValidacaoException ex) {
                Logger.getLogger(frmProdutoCad.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane,"Operação Não cancelada!");

        }
    }//GEN-LAST:event_btnFinalizarFuncionarioActionPerformed

    private void txtCadFuncionarioNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioNumeroActionPerformed

    private void txtNomeFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFuncionarioFocusLost
      
    }//GEN-LAST:event_txtNomeFuncionarioFocusLost

    private void btnFuncionarioCadTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioCadTelefoneActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente adicionar o numero de telefone?") == 0) {

            Telefone telefone = new Telefone();
            telefone.setNum(Integer.parseInt(txtCadtelefoneFuncionario.getText()));
           
            funcionario.addTelefone(telefone);
       
            JOptionPane.showMessageDialog(rootPane, "Telefone adicionado com sucesso!");
            addCamposTelefone();
            //limpar campo
            txtCadtelefoneFuncionario.setText(null);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada pelo usuário!");
        }
    }//GEN-LAST:event_btnFuncionarioCadTelefoneActionPerformed

    private void jtbCadListarTelefoneFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCadListarTelefoneFuncionarioMouseClicked
       if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar este campo?") == 0) {

            Telefone aux = new Telefone();
            Object valor = jtbCadListarTelefoneFuncionario.getValueAt( jtbCadListarTelefoneFuncionario.getSelectedRow(), 0);
            
            aux.setNum((int)valor);
            funcionario.removeTelefone(aux);
            //Chamar tabela novamente
            addCamposTelefone();
            
            JOptionPane.showMessageDialog(rootPane, "Campo limpo com sucesso!");
            
       }else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada!");
       }
      
      
    }//GEN-LAST:event_jtbCadListarTelefoneFuncionarioMouseClicked

    private void btnFuncionarioCadEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioCadEmailActionPerformed
         if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente adicionar esse E-mail?") == 0) {

            Email email = new Email();
            email.setEmail_nome(txtCadEmailFuncionario.getText());
           
            funcionario.addEmail(email);
       
            JOptionPane.showMessageDialog(rootPane, "E-mail adicionado com sucesso!");
            //Chamar tabela Email
            addCamposEmail();
            //limpar campo
            txtCadEmailFuncionario.setText(null);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada!");
        }
    }//GEN-LAST:event_btnFuncionarioCadEmailActionPerformed

    private void jtbFunListarEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbFunListarEmailMouseClicked
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar este campo?") == 0) {

            Email em = new Email();
            Object valor = jtbFunListarEmail.getValueAt( jtbFunListarEmail.getSelectedRow(), 0);
            
            em.setEmail_nome((String)valor);
            funcionario.removeEmail(em);
            //Chamar tabela novamente
            addCamposEmail();
            
            JOptionPane.showMessageDialog(rootPane, "Campo limpo com sucesso!");
            
       }else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada!");
       }
      
      
        
    }//GEN-LAST:event_jtbFunListarEmailMouseClicked

    private void btnFuncionarioCadEndeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioCadEndeEditarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente adicionar esse Endereço?") == 0) {

            Endereco endereco = new Endereco();
            endereco.setRua(txtCadFuncionarioRua.getText());
            try {
                endereco.setNum(Integer.parseInt(txtCadFuncionarioNumero.getText()));
            } catch (ErroValidacaoException ex) {
                Logger.getLogger(frmClienteCad.class.getName()).log(Level.SEVERE, null, ex);
            }
   
            endereco.setBairro(txtCadFuncionarioBairro.getText());
           
            funcionario.addEndereco(endereco);
       
            JOptionPane.showMessageDialog(rootPane, "Endereço adicionado com sucesso!");
            //Chamar tabela Email
            addCamposEndereco();
            //limpar campo
            txtCadFuncionarioRua.setText(null);
            txtCadFuncionarioNumero.setText(null);
            txtCadFuncionarioBairro.setText(null);
           
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada!");
        }
    }//GEN-LAST:event_btnFuncionarioCadEndeEditarActionPerformed

    private void jtbCadListarEndFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCadListarEndFuncionarioMouseClicked
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar este campo?") == 0) {

            Endereco en = new Endereco();
            Object valor1 = jtbCadListarEndFuncionario.getValueAt( jtbCadListarEndFuncionario.getSelectedRow(), 0);
            Object valor2 = jtbCadListarEndFuncionario.getValueAt( jtbCadListarEndFuncionario.getSelectedRow(), 1);
            Object valor3 = jtbCadListarEndFuncionario.getValueAt( jtbCadListarEndFuncionario.getSelectedRow(), 2);
            Object valor4 = jtbCadListarEndFuncionario.getValueAt( jtbCadListarEndFuncionario.getSelectedRow(), 3);
            Object valor5 = jtbCadListarEndFuncionario.getValueAt( jtbCadListarEndFuncionario.getSelectedRow(), 4);
            Object valor6 = jtbCadListarEndFuncionario.getValueAt( jtbCadListarEndFuncionario.getSelectedRow(), 5);
         
            en.setRua((String)valor1);
            try {
                en.setNum((int)valor2);
            } catch (ErroValidacaoException ex) {
                System.out.printf("Erro ao excluir linha da tabela Endereços, no cadastro de funcionario");
            }
            en.setBairro((String)valor3);
           
            
            funcionario.removeEndereco(en);
            //Chamar tabela novamente
            addCamposEndereco();
            
            JOptionPane.showMessageDialog(rootPane, "Campo limpo com sucesso!");
            
       }else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada!");
       }
    }//GEN-LAST:event_jtbCadListarEndFuncionarioMouseClicked

    private void pswSenhaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarFuncionario;
    private javax.swing.JButton btnFinalizarFuncionario;
    private javax.swing.JButton btnFuncionarioCadEmail;
    private javax.swing.JButton btnFuncionarioCadEndeEditar;
    private javax.swing.JButton btnFuncionarioCadEndeLimpar;
    private javax.swing.JButton btnFuncionarioCadTelefone;
    private javax.swing.JButton btnLimparFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpRemoverItemtbEndereco;
    private javax.swing.JPanel jpTituloClienteCad;
    private javax.swing.JPanel jpTituloRemoverItemTabEmail;
    private javax.swing.JPanel jpTituloRemoverItemTabTelefone;
    private javax.swing.JTable jtbCadListarEndFuncionario;
    private javax.swing.JTable jtbCadListarTelefoneFuncionario;
    private javax.swing.JTabbedPane jtbClienteCad;
    private javax.swing.JTable jtbFunListarEmail;
    private javax.swing.JLabel lblCadClienteBairro;
    private javax.swing.JLabel lblCadClienteEmail;
    private javax.swing.JLabel lblCadClienteEmail1;
    private javax.swing.JLabel lblCadClienteNumero;
    private javax.swing.JLabel lblCadClienteRua;
    private javax.swing.JLabel lblClienteCadNome;
    private javax.swing.JLabel lblCpfCad;
    private javax.swing.JLabel lblNascimentoCad;
    private javax.swing.JLabel lblRgCad;
    private javax.swing.JLabel lblTituloClienteCad;
    private javax.swing.JPasswordField pswSenhaCliente;
    private javax.swing.JTextField txtCadEmailFuncionario;
    private javax.swing.JTextField txtCadFuncionarioBairro;
    private javax.swing.JTextField txtCadFuncionarioNumero;
    private javax.swing.JTextField txtCadFuncionarioRua;
    private javax.swing.JTextField txtCadtelefoneFuncionario;
    private javax.swing.JTextField txtCpfFuncionario;
    private javax.swing.JTextField txtNascimentoFuncionario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtRgFuncionario;
    private javax.swing.JTextField txtUsuarioFuncionario;
    // End of variables declaration//GEN-END:variables
}
