/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ClienteDao;
import br.edu.ifnmg.trabalho.DataAccess.FuncionarioDao;
import br.edu.ifnmg.trabalho.classes.Cliente;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Funcionario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author emerson
 */
public class frmFuncionarioEditar extends javax.swing.JInternalFrame {
    Funcionario  funcionario;
    FuncionarioDao dao;

    /**
     * Creates new form frmClienteEditar
     */
    public frmFuncionarioEditar(Funcionario c, FuncionarioDao d) throws ErroValidacaoException, ParseException {
        initComponents();
        this.funcionario = c;
        this.dao = d;
        
        carregaCampos();
    }
    
    public Date DataF(String dataDesformatada) throws ParseException{
        
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");  
        Date dataForm = format.parse(dataDesformatada);
        
      
        return dataForm; 
    }
    
    private void carregaCampos() throws ErroValidacaoException, ParseException {
        txtEditarFuncionarioId.setText(Integer.toString(funcionario.getId()));
        txtEditarFuncionarioNome.setText(funcionario.getNome());
        txtEditarFuncionarioCpf.setText(Integer.toString(funcionario.getCpf()));
        txtEditarFuncionarioRg.setText(Integer.toString(funcionario.getRg()));
        txtEditarFuncionarioNascimento.setText(funcionario.getDataRetorno());
        txtEditarFuncionarioUsuario.setText(funcionario.getUsuario());
        txtEditarFuncionarioSenha.setText(funcionario.getSenha());

    }

    private void carregaObjeto() {
        try{
        funcionario.setId(Integer.parseInt(txtEditarFuncionarioId.getText()));
        funcionario.setNome(txtEditarFuncionarioNome.getText());
        funcionario.setCpf(Integer.parseInt(txtEditarFuncionarioCpf.getText()));
        funcionario.setRg(Integer.parseInt(txtEditarFuncionarioRg.getText()));
        funcionario.setData(DataF(txtEditarFuncionarioNascimento.getText()));
        funcionario.setUsuario(txtEditarFuncionarioUsuario.getText());
        funcionario.setSenha(txtEditarFuncionarioSenha.getText());
      
        }catch (Exception ex){
            System.out.print("Erro ao transefir os dados para o objeto");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEditarFuncionarioId = new javax.swing.JTextField();
        txtEditarFuncionarioNome = new javax.swing.JTextField();
        txtEditarFuncionarioCpf = new javax.swing.JTextField();
        txtEditarFuncionarioRg = new javax.swing.JTextField();
        txtEditarFuncionarioNascimento = new javax.swing.JTextField();
        btnEditarFuncionarioApagar = new javax.swing.JButton();
        btnEditarFuncionarioSalvar = new javax.swing.JButton();
        jpTituloPagamentoEditar = new javax.swing.JPanel();
        lblTituloPagamentoEditar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEditarFuncionarioUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEditarFuncionarioSenha = new javax.swing.JPasswordField();

        setClosable(true);

        jLabel1.setText("Id");

        jLabel2.setText("Nome");

        jLabel3.setText("Cpf");

        jLabel4.setText("Rg");

        jLabel5.setText("Nascimento");

        txtEditarFuncionarioId.setEnabled(false);

        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##-##-####");
            txtEditarFuncionarioNascimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        btnEditarFuncionarioApagar.setText("Apagar");
        btnEditarFuncionarioApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncionarioApagarActionPerformed(evt);
            }
        });

        btnEditarFuncionarioSalvar.setText("Salvar");
        btnEditarFuncionarioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncionarioSalvarActionPerformed(evt);
            }
        });

        jpTituloPagamentoEditar.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloPagamentoEditar.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloPagamentoEditar.setText("Editar Funcionario");

        javax.swing.GroupLayout jpTituloPagamentoEditarLayout = new javax.swing.GroupLayout(jpTituloPagamentoEditar);
        jpTituloPagamentoEditar.setLayout(jpTituloPagamentoEditarLayout);
        jpTituloPagamentoEditarLayout.setHorizontalGroup(
            jpTituloPagamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloPagamentoEditarLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblTituloPagamentoEditar)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jpTituloPagamentoEditarLayout.setVerticalGroup(
            jpTituloPagamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloPagamentoEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPagamentoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Usuario");

        jLabel7.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloPagamentoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEditarFuncionarioId, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(txtEditarFuncionarioNome)
                    .addComponent(txtEditarFuncionarioCpf)
                    .addComponent(txtEditarFuncionarioRg)
                    .addComponent(txtEditarFuncionarioNascimento)
                    .addComponent(txtEditarFuncionarioUsuario)
                    .addComponent(txtEditarFuncionarioSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarFuncionarioApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarFuncionarioSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloPagamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEditarFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEditarFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEditarFuncionarioCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtEditarFuncionarioRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtEditarFuncionarioNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarFuncionarioSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarFuncionarioApagar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtEditarFuncionarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEditarFuncionarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarFuncionarioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioSalvarActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Salvar?") == 0) {

                carregaObjeto();
                
                if (dao.Salvar(funcionario,0)) {
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmFuncionarioListar janela = new frmFuncionarioListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao salvar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnEditarFuncionarioSalvarActionPerformed

    private void btnEditarFuncionarioApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioApagarActionPerformed
       try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente apagar funcionario?") == 0) {

                carregaObjeto();
                
                if (dao.Apagar(funcionario)) {
                    JOptionPane.showMessageDialog(rootPane, "Funcionario deletado com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmFuncionarioListar janela = new frmFuncionarioListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao apagar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnEditarFuncionarioApagarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarFuncionarioApagar;
    private javax.swing.JButton btnEditarFuncionarioSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jpTituloPagamentoEditar;
    private javax.swing.JLabel lblTituloPagamentoEditar;
    private javax.swing.JTextField txtEditarFuncionarioCpf;
    private javax.swing.JTextField txtEditarFuncionarioId;
    private javax.swing.JTextField txtEditarFuncionarioNascimento;
    private javax.swing.JTextField txtEditarFuncionarioNome;
    private javax.swing.JTextField txtEditarFuncionarioRg;
    private javax.swing.JPasswordField txtEditarFuncionarioSenha;
    private javax.swing.JTextField txtEditarFuncionarioUsuario;
    // End of variables declaration//GEN-END:variables
}
