/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.PagamentoDao;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Pagamento;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author emerson
 */
public class frmPagamentoListar extends javax.swing.JInternalFrame {
    PagamentoDao dao;
    /**
     * Creates new form frmListarProduto
     */
    public frmPagamentoListar() throws ErroValidacaoException {
        initComponents();
        dao = new PagamentoDao();
        
        List<Pagamento> pagamentos = dao.listarTodos();
        
        preencheTabela(pagamentos);
    }
    
    //Metodo para listar Produtos na Tabela tblListagemProd
    private void preencheTabela(List<Pagamento> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nome");
        model.addColumn("Juros(%)");
       
        
        for (Pagamento paga : lista) {
            Vector valores = new Vector();
            valores.add(0,paga.getId());
            valores.add(1,paga.getNome());
            valores.add(2,paga.getJuros());
           
            
            model.addRow(valores);
        }
        tblListagemPaga.setModel(model);
        tblListagemPaga.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomePaga = new javax.swing.JLabel();
        txtFiltrarPaga = new javax.swing.JTextField();
        btnFiltrarPaga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagemPaga = new javax.swing.JTable();
        jpTituloPagamentoListar = new javax.swing.JPanel();
        lblTituloPagamentoListar = new javax.swing.JLabel();
        lblTituloPagamentoListar2 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(600, 380));

        lblNomePaga.setText("Nome");

        btnFiltrarPaga.setText("Filtrar");
        btnFiltrarPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarPagaActionPerformed(evt);
            }
        });

        tblListagemPaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListagemPaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemPagaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagemPaga);

        jpTituloPagamentoListar.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloPagamentoListar.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        lblTituloPagamentoListar.setText("Clique sobre a forma de pagamento para editar.");

        lblTituloPagamentoListar2.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloPagamentoListar2.setText("Listagem de Pagamentos");

        javax.swing.GroupLayout jpTituloPagamentoListarLayout = new javax.swing.GroupLayout(jpTituloPagamentoListar);
        jpTituloPagamentoListar.setLayout(jpTituloPagamentoListarLayout);
        jpTituloPagamentoListarLayout.setHorizontalGroup(
            jpTituloPagamentoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloPagamentoListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPagamentoListar2)
                .addGap(141, 141, 141))
            .addGroup(jpTituloPagamentoListarLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblTituloPagamentoListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTituloPagamentoListarLayout.setVerticalGroup(
            jpTituloPagamentoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloPagamentoListarLayout.createSequentialGroup()
                .addComponent(lblTituloPagamentoListar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPagamentoListar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloPagamentoListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomePaga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrarPaga, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrarPaga)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloPagamentoListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrarPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomePaga)
                    .addComponent(btnFiltrarPaga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarPagaActionPerformed
        Pagamento paga = new Pagamento();
        try{
            paga.setNome(txtFiltrarPaga.getText());
        }catch(Exception ex){
            System.out.printf("Erro");
        }
        
        List<Pagamento> lista = null;
        try {
            lista = dao.buscar(paga);
        } catch (ErroValidacaoException ex) {
            System.out.printf("Erro");
        }
        
        preencheTabela(lista);
    }//GEN-LAST:event_btnFiltrarPagaActionPerformed

    private void tblListagemPagaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemPagaMouseClicked
        Object valor = tblListagemPaga.getValueAt( tblListagemPaga.getSelectedRow(), 0);
        Pagamento paga = null;
        try {
            paga = dao.Abrir((int)valor);
        } catch (ErroValidacaoException ex) {
            System.out.printf("Erro");        }
        frmPagamentoEditar janela = new frmPagamentoEditar(paga, dao);
        this.getParent().add(janela);
        janela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tblListagemPagaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarPaga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpTituloPagamentoListar;
    private javax.swing.JLabel lblNomePaga;
    private javax.swing.JLabel lblTituloPagamentoListar;
    private javax.swing.JLabel lblTituloPagamentoListar2;
    private javax.swing.JTable tblListagemPaga;
    private javax.swing.JTextField txtFiltrarPaga;
    // End of variables declaration//GEN-END:variables
}
