/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.PagamentoDao;
import br.edu.ifnmg.trabalho.DataAccess.ProdutoDao;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Pagamento;
import br.edu.ifnmg.trabalho.classes.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author emerson
 */
public class frmPagamentoEditar extends javax.swing.JInternalFrame {
    Pagamento pagamento;
    PagamentoDao dao;
    /**
     * Creates new form frmProdutoEditar
     */
    public frmPagamentoEditar(Pagamento p, PagamentoDao d) {
        initComponents();
        this.pagamento = p;
        this.dao = d;
        
        carregaCampos();
       
    }
    
     private void carregaCampos() {
        txtEditarPagaId.setText(Integer.toString(pagamento.getId()));
        txtEditarPagaNome.setText(pagamento.getNome());
        txtEditarPagaJuros.setText(Double.toString(pagamento.getJuros()));
        
        
    }

    private void carregaObjeto() {
        try{
        pagamento.setId(Integer.parseInt(txtEditarPagaId.getText()));
        pagamento.setNome(txtEditarPagaNome.getText());
        pagamento.setJuros(Double.parseDouble(txtEditarPagaJuros.getText()));
        
       
        }catch (Exception ex){
            System.out.print("Erro");
        }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTituloPagamentoEditar = new javax.swing.JPanel();
        lblTituloPagamentoEditar = new javax.swing.JLabel();
        lblEditarIdPaga = new javax.swing.JLabel();
        lblEditarNomePaga = new javax.swing.JLabel();
        lblEditarJurosPaga = new javax.swing.JLabel();
        txtEditarPagaNome = new javax.swing.JTextField();
        txtEditarPagaJuros = new javax.swing.JTextField();
        btnAlterarPagamento = new javax.swing.JButton();
        btnCancelarEdicaoPagamento = new javax.swing.JButton();
        txtEditarPagaId = new javax.swing.JTextField();
        btnApagarPagamento = new javax.swing.JButton();

        setClosable(true);

        jpTituloPagamentoEditar.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloPagamentoEditar.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloPagamentoEditar.setText("Editar Pagamento");

        javax.swing.GroupLayout jpTituloPagamentoEditarLayout = new javax.swing.GroupLayout(jpTituloPagamentoEditar);
        jpTituloPagamentoEditar.setLayout(jpTituloPagamentoEditarLayout);
        jpTituloPagamentoEditarLayout.setHorizontalGroup(
            jpTituloPagamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloPagamentoEditarLayout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(lblTituloPagamentoEditar)
                .addGap(187, 187, 187))
        );
        jpTituloPagamentoEditarLayout.setVerticalGroup(
            jpTituloPagamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloPagamentoEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPagamentoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEditarIdPaga.setText("Id");

        lblEditarNomePaga.setText("Nome");

        lblEditarJurosPaga.setText("Juros");

        txtEditarPagaJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarPagaJurosActionPerformed(evt);
            }
        });

        btnAlterarPagamento.setText("Alterar");
        btnAlterarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPagamentoActionPerformed(evt);
            }
        });

        btnCancelarEdicaoPagamento.setText("Limpar");
        btnCancelarEdicaoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEdicaoPagamentoActionPerformed(evt);
            }
        });

        txtEditarPagaId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEditarPagaId.setEnabled(false);

        btnApagarPagamento.setText("Apagar");
        btnApagarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloPagamentoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEditarIdPaga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEditarPagaId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditarNomePaga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEditarJurosPaga, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditarPagaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditarPagaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApagarPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarEdicaoPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloPagamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterarPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagarPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarEdicaoPagamento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarPagaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditarIdPaga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarPagaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditarNomePaga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEditarJurosPaga)
                            .addComponent(txtEditarPagaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPagamentoActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Salvar?") == 0) {

                carregaObjeto();
                
                if (dao.Salvar(pagamento)) {
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmPagamentoListar janela = new frmPagamentoListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                 
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao salvar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnAlterarPagamentoActionPerformed

    private void btnApagarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarPagamentoActionPerformed
         try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente apagar esta forma de pagamento?") == 0) {

                carregaObjeto();
                
                if (dao.Apagar(pagamento)) {
                    JOptionPane.showMessageDialog(rootPane, "Pagamento deletado com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmPagamentoListar janela = new frmPagamentoListar();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao apagar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnApagarPagamentoActionPerformed

    private void txtEditarPagaJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarPagaJurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarPagaJurosActionPerformed

    private void btnCancelarEdicaoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicaoPagamentoActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar os seguintes campos?") == 0) {
            txtEditarPagaNome.setText(null);
            txtEditarPagaJuros.setText(null);

            
            JOptionPane.showMessageDialog(rootPane, "Os Campos foram limpos!");
   
        } else {                
            JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
        }
    }//GEN-LAST:event_btnCancelarEdicaoPagamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPagamento;
    private javax.swing.JButton btnApagarPagamento;
    private javax.swing.JButton btnCancelarEdicaoPagamento;
    private javax.swing.JPanel jpTituloPagamentoEditar;
    private javax.swing.JLabel lblEditarIdPaga;
    private javax.swing.JLabel lblEditarJurosPaga;
    private javax.swing.JLabel lblEditarNomePaga;
    private javax.swing.JLabel lblTituloPagamentoEditar;
    private javax.swing.JTextField txtEditarPagaId;
    private javax.swing.JTextField txtEditarPagaJuros;
    private javax.swing.JTextField txtEditarPagaNome;
    // End of variables declaration//GEN-END:variables
}
