/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ProdutoDao;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author emerson
 */
public class frmProdutoEditar extends javax.swing.JInternalFrame {
    Produto produto;
    ProdutoDao dao;
    /**
     * Creates new form frmProdutoEditar
     */
    public frmProdutoEditar(Produto p, ProdutoDao d) {
        initComponents();
        this.produto = p;
        this.dao = d;
        
        carregaCampos();
       
    }
    
     private void carregaCampos() {
        txtEditarProdId.setText(Integer.toString(produto.getId()));
        txtEditarProdNome.setText(produto.getNome());
        txtEditarProdCompra.setText(Double.toString(produto.getValor_comp()));
        txtEditarProdVenda.setText(Double.toString(produto.getValor_vend()));
        txtEditarProdDescricao.setText(produto.getDescricao());
        txtEditarProdEstoque.setText(Integer.toString(produto.getEstoque()));
        
    }

    private void carregaObjeto() {
        try{
        produto.setId(Integer.parseInt(txtEditarProdId.getText()));
        produto.setNome(txtEditarProdNome.getText());
        produto.setValor_comp(Double.parseDouble(txtEditarProdCompra.getText()));
        produto.setValor_vend(Double.parseDouble(txtEditarProdVenda.getText()));
        produto.setDescricao(txtEditarProdDescricao.getText());
        produto.setEstoque(Integer.parseInt(txtEditarProdEstoque.getText()));
        
        }catch (ErroValidacaoException ex){
            System.out.print("Erro");
        }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEditarProdNome = new javax.swing.JTextField();
        txtEditarProdDescricao = new javax.swing.JTextField();
        txtEditarProdCompra = new javax.swing.JTextField();
        txtEditarProdVenda = new javax.swing.JTextField();
        txtEditarProdEstoque = new javax.swing.JTextField();
        btnAlterarProduto = new javax.swing.JButton();
        btnCancelarEdicaoProduto = new javax.swing.JButton();
        txtEditarProdId = new javax.swing.JTextField();
        btnApagarProduto = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Editar Produto");

        javax.swing.GroupLayout jtituloLayout = new javax.swing.GroupLayout(jtitulo);
        jtitulo.setLayout(jtituloLayout);
        jtituloLayout.setHorizontalGroup(
            jtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(188, 188, 188))
        );
        jtituloLayout.setVerticalGroup(
            jtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Id");

        jLabel3.setText("Nome");

        jLabel4.setText("Valor Compra");

        jLabel5.setText("Valor Venda");

        jLabel6.setText("Descrição");

        jLabel7.setText("Estoque");

        txtEditarProdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarProdVendaActionPerformed(evt);
            }
        });

        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnCancelarEdicaoProduto.setText("Cancelar");

        txtEditarProdId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEditarProdId.setEnabled(false);

        btnApagarProduto.setText("Apagar");
        btnApagarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAlterarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarEdicaoProduto))
                            .addComponent(txtEditarProdEstoque)
                            .addComponent(txtEditarProdDescricao)
                            .addComponent(txtEditarProdVenda)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditarProdCompra)
                            .addComponent(txtEditarProdNome)
                            .addComponent(txtEditarProdId))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEditarProdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEditarProdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEditarProdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEditarProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditarProdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEditarProdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnCancelarEdicaoProduto)
                    .addComponent(btnApagarProduto))
                .addGap(0, 67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditarProdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarProdVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarProdVendaActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Salvar?") == 0) {

                carregaObjeto();
                
                if (dao.Salvar(produto)) {
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmListarProduto janela = new frmListarProduto();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                 
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao salvar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void btnApagarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarProdutoActionPerformed
         try {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente apagar este produto?") == 0) {

                carregaObjeto();
                
                if (dao.Apagar(produto)) {
                    JOptionPane.showMessageDialog(rootPane, "Produto deletado com sucesso!");
                    
                    //Chamar NOVAMENTE a janela de listagem de Produtos
                    frmListarProduto janela = new frmListarProduto();
                    this.getParent().add(janela);
                    janela.setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao apagar! Consulte o administrador do sistema!");
                }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar! Consulte o administrador do sistema!");
        }
    }//GEN-LAST:event_btnApagarProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnApagarProduto;
    private javax.swing.JButton btnCancelarEdicaoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jtitulo;
    private javax.swing.JTextField txtEditarProdCompra;
    private javax.swing.JTextField txtEditarProdDescricao;
    private javax.swing.JTextField txtEditarProdEstoque;
    private javax.swing.JTextField txtEditarProdId;
    private javax.swing.JTextField txtEditarProdNome;
    private javax.swing.JTextField txtEditarProdVenda;
    // End of variables declaration//GEN-END:variables
}
