/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ProdutoDao;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Produto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author emerson
 */
public class frmProdutoInterno extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProdutoInterno
     */
    public frmProdutoInterno() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtValorCompraProd = new javax.swing.JTextField();
        txtValorVendaProd = new javax.swing.JTextField();
        txtDescricaoProd = new javax.swing.JTextField();
        btnFinalizarProd = new javax.swing.JButton();
        btnCancelarProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEstoqueProd = new javax.swing.JTextField();

        jLabel1.setText("Nome");

        jLabel2.setText("Preço Compra");

        jLabel3.setText("Preço Venda");

        jLabel4.setText("Descrição");

        txtValorVendaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorVendaProdActionPerformed(evt);
            }
        });

        btnFinalizarProd.setText("Finalizar");
        btnFinalizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarProdActionPerformed(evt);
            }
        });

        btnCancelarProd.setText("Cancelar");
        btnCancelarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdActionPerformed(evt);
            }
        });

        jLabel5.setText("Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorCompraProd)
                            .addComponent(txtNomeProd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFinalizarProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarProd))
                            .addComponent(txtDescricaoProd)
                            .addComponent(txtValorVendaProd)
                            .addComponent(txtEstoqueProd))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorCompraProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescricaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEstoqueProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarProd)
                    .addComponent(btnCancelarProd))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorVendaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVendaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVendaProdActionPerformed

    private void btnCancelarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane,  "Deseja Cancelar?") == 0){              
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada");
            this.dispose();
        } else {               
            JOptionPane.showMessageDialog(rootPane,"Operação Não cancelada!");
            
        }
        
        
    }//GEN-LAST:event_btnCancelarProdActionPerformed

    private void btnFinalizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarProdActionPerformed
         if(JOptionPane.showConfirmDialog(rootPane,  "Deseja Salvar?") == 0){  
            try {
                Produto prod = new Produto();
                
                //Setando os dados e convertendo de text para seus respectivos tipos.
                prod.setNome(txtNomeProd.getText());
                prod.setValor_comp(Double.parseDouble(txtValorCompraProd.getText()));
                prod.setValor_vend(Double.parseDouble(txtValorVendaProd.getText()));
                prod.setDescricao(txtDescricaoProd.getText());
                prod.setEstoque(Integer.parseInt(txtEstoqueProd.getText()));
                
                //Criando variavel dao para salvar os dados no BD.
                ProdutoDao dao = new ProdutoDao();
                //mandando prod para dao.Salvar.
                dao.Salvar(prod);
                
                //Mensagem de confirmação!
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso");
                
                //Limpando campos do formularios para o usuarios nao inserir os mesmos dados novamente.
                txtNomeProd.setText(null);
                txtValorCompraProd.setText(null);
                txtValorVendaProd.setText(null);
                txtDescricaoProd.setText(null);
                txtEstoqueProd.setText(null);
                
            } catch (ErroValidacaoException ex) {
                Logger.getLogger(frmProdutoInterno.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {               
            JOptionPane.showMessageDialog(rootPane,"Operação Não cancelada!");
            
        }
    }//GEN-LAST:event_btnFinalizarProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProd;
    private javax.swing.JButton btnFinalizarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescricaoProd;
    private javax.swing.JTextField txtEstoqueProd;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtValorCompraProd;
    private javax.swing.JTextField txtValorVendaProd;
    // End of variables declaration//GEN-END:variables
}
