/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author emerson
 */
public class frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipal
     */
    public frmprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jmMenuPrincipal = new javax.swing.JMenuBar();
        jmCadCliente = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmCadFuncionario = new javax.swing.JMenuItem();
        jmCadProduto = new javax.swing.JMenuItem();
        jmCadPagamento = new javax.swing.JMenuItem();
        jmCadVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmClienteListar1 = new javax.swing.JMenuItem();
        jmListarFuncionarios = new javax.swing.JMenuItem();
        jmPagamentoListar = new javax.swing.JMenuItem();
        jmProdutoListar = new javax.swing.JMenuItem();
        jmListarVendas = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCadCliente.setText("Cadastrar");

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmCadCliente.add(jmiCliente);

        jmCadFuncionario.setText("Funcionario");
        jmCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadFuncionarioActionPerformed(evt);
            }
        });
        jmCadCliente.add(jmCadFuncionario);

        jmCadProduto.setText("Produto");
        jmCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadProdutoActionPerformed(evt);
            }
        });
        jmCadCliente.add(jmCadProduto);

        jmCadPagamento.setText("Pagamento");
        jmCadPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadPagamentoActionPerformed(evt);
            }
        });
        jmCadCliente.add(jmCadPagamento);

        jmCadVenda.setText("Venda");
        jmCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadVendaActionPerformed(evt);
            }
        });
        jmCadCliente.add(jmCadVenda);

        jmMenuPrincipal.add(jmCadCliente);

        jMenu3.setText("Listar");

        jmClienteListar1.setText("Clientes");
        jmClienteListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteListar1ActionPerformed(evt);
            }
        });
        jMenu3.add(jmClienteListar1);

        jmListarFuncionarios.setText("Funcionario");
        jmListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarFuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(jmListarFuncionarios);

        jmPagamentoListar.setText("Forma Pagamento");
        jmPagamentoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPagamentoListarActionPerformed(evt);
            }
        });
        jMenu3.add(jmPagamentoListar);

        jmProdutoListar.setText("Produto");
        jmProdutoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProdutoListarActionPerformed(evt);
            }
        });
        jMenu3.add(jmProdutoListar);

        jmListarVendas.setText("Vendas");
        jmListarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jmListarVendas);

        jmMenuPrincipal.add(jMenu3);

        setJMenuBar(jmMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        frmClienteCad janela = new frmClienteCad();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadFuncionarioActionPerformed
        frmFuncionarioCad janela = new frmFuncionarioCad();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmCadFuncionarioActionPerformed

    private void jmCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadProdutoActionPerformed
        frmProdutoCad janela = new frmProdutoCad();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmCadProdutoActionPerformed

    private void jmCadPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadPagamentoActionPerformed
        frmPagamentoCad janela = new frmPagamentoCad();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmCadPagamentoActionPerformed

    private void jmCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadVendaActionPerformed
       frmVenda janela = null;
        try {
            try {
                janela = new frmVenda();
            } catch (ParseException ex) {
                Logger.getLogger(frmprincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(frmprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       add(janela);
       janela.setVisible(true);
    }//GEN-LAST:event_jmCadVendaActionPerformed

    private void jmProdutoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProdutoListarActionPerformed
        frmProdutoListar janela = null;
        try {
            janela = new frmProdutoListar();
        } catch (ErroValidacaoException ex) {
            System.out.printf("Erro");
        }
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmProdutoListarActionPerformed

    private void jmListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarVendasActionPerformed
        frmVendaListar janela = new frmVendaListar();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmListarVendasActionPerformed

    private void jmPagamentoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPagamentoListarActionPerformed
        frmPagamentoListar janela = null;
        try {
            janela = new frmPagamentoListar();
        } catch (ErroValidacaoException ex) {
            System.out.printf("erro");
        }
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmPagamentoListarActionPerformed

    private void jmListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarFuncionariosActionPerformed
        frmFuncionarioListar janela = null;
        try {        
            janela = new frmFuncionarioListar();
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(frmprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(frmprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        add(janela);
        janela.setVisible(true);
        
    }//GEN-LAST:event_jmListarFuncionariosActionPerformed

    private void jmClienteListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteListar1ActionPerformed
        // TODO add your handling code here:
        frmClienteListar janela = null;
        try {
            janela = new frmClienteListar();
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(frmprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(frmprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmClienteListar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jmCadCliente;
    private javax.swing.JMenuItem jmCadFuncionario;
    private javax.swing.JMenuItem jmCadPagamento;
    private javax.swing.JMenuItem jmCadProduto;
    private javax.swing.JMenuItem jmCadVenda;
    private javax.swing.JMenuItem jmClienteListar1;
    private javax.swing.JMenuItem jmListarFuncionarios;
    private javax.swing.JMenuItem jmListarVendas;
    private javax.swing.JMenuBar jmMenuPrincipal;
    private javax.swing.JMenuItem jmPagamentoListar;
    private javax.swing.JMenuItem jmProdutoListar;
    private javax.swing.JMenuItem jmiCliente;
    // End of variables declaration//GEN-END:variables
}
