/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.telas;

import br.edu.ifnmg.trabalho.DataAccess.ProdutoDao;
import br.edu.ifnmg.trabalho.classes.ErroValidacaoException;
import br.edu.ifnmg.trabalho.classes.Produto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author emerson
 */
public class frmProdutoCad extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProdutoInterno
     */
    public frmProdutoCad() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtValorCompraProd = new javax.swing.JTextField();
        txtValorVendaProd = new javax.swing.JTextField();
        txtDescricaoProd = new javax.swing.JTextField();
        btnFinalizarProd = new javax.swing.JButton();
        btnCancelarProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEstoqueProd = new javax.swing.JTextField();
        btnLimparProd = new javax.swing.JButton();
        jpTituloProdutoCad = new javax.swing.JPanel();
        lblTituloProdutoCad = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Nome");

        jLabel2.setText("Preço Compra");

        jLabel3.setText("Preço Venda");

        jLabel4.setText("Descrição");

        txtValorCompraProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCompraProdActionPerformed(evt);
            }
        });

        txtValorVendaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorVendaProdActionPerformed(evt);
            }
        });

        txtDescricaoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoProdActionPerformed(evt);
            }
        });

        btnFinalizarProd.setText("Finalizar");
        btnFinalizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarProdActionPerformed(evt);
            }
        });

        btnCancelarProd.setText("Cancelar");
        btnCancelarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdActionPerformed(evt);
            }
        });

        jLabel5.setText("Estoque");

        txtEstoqueProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueProdActionPerformed(evt);
            }
        });

        btnLimparProd.setText("Limpar");
        btnLimparProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparProdActionPerformed(evt);
            }
        });

        jpTituloProdutoCad.setBackground(new java.awt.Color(0, 102, 153));

        lblTituloProdutoCad.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloProdutoCad.setText("Cadastrar Produto");

        javax.swing.GroupLayout jpTituloProdutoCadLayout = new javax.swing.GroupLayout(jpTituloProdutoCad);
        jpTituloProdutoCad.setLayout(jpTituloProdutoCadLayout);
        jpTituloProdutoCadLayout.setHorizontalGroup(
            jpTituloProdutoCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloProdutoCadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloProdutoCad)
                .addGap(183, 183, 183))
        );
        jpTituloProdutoCadLayout.setVerticalGroup(
            jpTituloProdutoCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloProdutoCadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloProdutoCad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstoqueProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorVendaProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorCompraProd, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimparProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarProd))
                .addContainerGap(84, Short.MAX_VALUE))
            .addComponent(jpTituloProdutoCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloProdutoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorCompraProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtValorVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDescricaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEstoqueProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFinalizarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarProd)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorVendaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVendaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVendaProdActionPerformed

    private void btnCancelarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane,  "Deseja Cancelar?") == 0){              
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada");
            this.dispose();
        } else {               
            JOptionPane.showMessageDialog(rootPane,"Operação Não cancelada!");
            
        }
        
        
    }//GEN-LAST:event_btnCancelarProdActionPerformed

    private void btnFinalizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarProdActionPerformed
         if(JOptionPane.showConfirmDialog(rootPane,  "Deseja Salvar?") == 0){  
            try {
                Produto prod = new Produto();
                
                //Setando os dados e convertendo de text para seus respectivos tipos.
                prod.setNome(txtNomeProd.getText());
                prod.setValor_comp(Double.parseDouble(txtValorCompraProd.getText()));
                prod.setValor_vend(Double.parseDouble(txtValorVendaProd.getText()));
                prod.setDescricao(txtDescricaoProd.getText());
                prod.setEstoque(Integer.parseInt(txtEstoqueProd.getText()));
                
                //Criando variavel dao para salvar os dados no BD.
                ProdutoDao dao = new ProdutoDao();
                //mandando prod para dao.Salvar.
                //Mensagem de confirmação!
                if(dao.Salvar(prod)){
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! Consulte o administrador do sistema");
                }
                
                //Limpando campos do formularios para o usuarios nao inserir os mesmos dados novamente.
                txtNomeProd.setText(null);
                txtValorCompraProd.setText(null);
                txtValorVendaProd.setText(null);
                txtDescricaoProd.setText(null);
                txtEstoqueProd.setText(null);
                
            } catch (ErroValidacaoException ex) {
                Logger.getLogger(frmProdutoCad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {               
            JOptionPane.showMessageDialog(rootPane,"Operação Não cancelada!");
            
        }
    }//GEN-LAST:event_btnFinalizarProdActionPerformed

    private void txtValorCompraProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompraProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraProdActionPerformed

    private void txtEstoqueProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueProdActionPerformed

    private void txtDescricaoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoProdActionPerformed

    private void btnLimparProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparProdActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente limpar os seguintes campos?") == 0) {
            txtNomeProd.setText(null);
            txtValorCompraProd.setText(null);
            txtValorVendaProd.setText(null);
            txtDescricaoProd.setText(null);
            txtEstoqueProd.setText(null);
            
            JOptionPane.showMessageDialog(rootPane, "Os Campos foram limpos!");
   
        } else {                
            JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
        }
    }//GEN-LAST:event_btnLimparProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProd;
    private javax.swing.JButton btnFinalizarProd;
    private javax.swing.JButton btnLimparProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jpTituloProdutoCad;
    private javax.swing.JLabel lblTituloProdutoCad;
    private javax.swing.JTextField txtDescricaoProd;
    private javax.swing.JTextField txtEstoqueProd;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtValorCompraProd;
    private javax.swing.JTextField txtValorVendaProd;
    // End of variables declaration//GEN-END:variables
}
